### ISSUE TITLE
Parse issue when installing

### ISSUE THREAD

**Issue by SpaceTy** [JeanSchoeller/iio-hyprland#25]
# When I try to install using the command 
## it buggs out with the following response:
```~ » yay iio-hyprland-git                                                         st@Space-Arch
1 aur/iio-hyprland-git r27.5c79b99-2.0 (+1 0.00)
    Reads iio-proxy-sensor output to enable automatic touchscreen rotation in Hyprland
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
AUR Explicit (1): iio-hyprland-git-r27.5c79b99-2.0
Sync Dependency (1): iio-sensor-proxy-3.5-2
:: (1/1) Downloaded PKGBUILD: iio-hyprland
  1 iio-hyprland                     (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/1): /home/st/.cache/yay/iio-hyprland
HEAD is now at 065498c Publishing v2 using the Hyprctl inputs
Removing iio-hyprland/
Removing src/
  1 iio-hyprland                     (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
==> Making package: iio-hyprland r27.5c79b99-2.0 (Mon Sep  9 21:17:23 2024)
==> Retrieving sources...
  -> Cloning iio-hyprland git repo...
Cloning into bare repository '/home/st/.cache/yay/iio-hyprland/iio-hyprland'...
remote: Enumerating objects: 187, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 187 (delta 37), reused 36 (delta 17), pack-reused 118 (from 1)
Receiving objects: 100% (187/187), 59.38 KiB | 690.00 KiB/s, done.
Resolving deltas: 100% (94/94), done.
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha1sums...
    iio-hyprland ... Skipped
:: (1/1) Parsing SRCINFO: iio-hyprland
 -> failed to parse iio-hyprland: Line 4: key "pkgver" can not occur after pkgname: pkgver = r27.5c79b99goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
main.main.func2()
	github.com/Jguer/yay/v12/main.go:125 +0x45
panic({0x5c40151533c0?, 0xc000160f40?})
	runtime/panic.go:785 +0x132
github.com/Jguer/yay/v12/pkg/sync/srcinfo.NewService({0x5c40151db9f0, 0xc00012c240}, 0xc000148200, 0xc00024c1e0, {0x5c40151d8fb8, 0xc0000f26c0}, {0x5c40151d7e70, 0xc00007f780}, 0xc00022a600)
	github.com/Jguer/yay/v12/pkg/sync/srcinfo/service.go:37 +0x1c7
github.com/Jguer/yay/v12/pkg/sync.(*OperationService).Run(0xc00022a180, {0x5c40151d6c30, 0x5c40154b12e0}, 0xc000125500, 0xc000151cb0, {0xc0000362c0, 0x2, 0x2}, {0x5c40154b12e0, 0x0, ...})
	github.com/Jguer/yay/v12/pkg/sync/sync.go:74 +0xd7f
main.syncInstall({0x5c40151d6c30, 0x5c40154b12e0}, 0xc000125500, 0xc000151cb0, {0x5c40151db9f0, 0xc00012c240})
	github.com/Jguer/yay/v12/sync.go:90 +0xf1a
main.displayNumberMenu({0x5c40151d6c30, 0x5c40154b12e0}, 0xc000125500, {0xc000037f70, 0x1, 0x1}, {0x5c40151db9f0, 0xc00012c240}, {0x5c40151d6e28, 0xc000125490}, ...)
	github.com/Jguer/yay/v12/cmd.go:414 +0x26c
main.handleYay({0x5c40151d6c30, 0x5c40154b12e0}, 0xc000125500, 0xc000151cb0, {0x5c40151d8fb8, 0xc0000f26c0}, {0x5c40151db9f0, 0xc00012c240}, {0x5c40151d6e28, 0xc000125490})
	github.com/Jguer/yay/v12/cmd.go:292 +0x3e6
main.handleCmd({0x5c40151d6c30, 0x5c40154b12e0}, 0xc000125500, 0xc000151cb0, {0x5c40151db9f0, 0xc00012c240})
	github.com/Jguer/yay/v12/cmd.go:180 +0x310
main.main()
	github.com/Jguer/yay/v12/main.go:131 +0x66a```
	
	I am on an `Asus Rog flow x 13 GV301RA` using arch linux with hyprland. I am new to linux, so might have done something wrong, but I have no idea why this is happening and seems to be a project issue. I would appreciate if you guys fixed it, thanks for your work.

**Comment by JeanSchoeller** [comment]
Arrh, I thought this was fixed. I'll check tonight. It's a pkgver issue.

**Comment by katulevskiy** [comment]
Having the same issue.

**Comment by JeanSchoeller** [comment]
Shit. I thought it was fixed.
Try building from scratch for now. 
I will fix AUR package ASAP.

**Comment by Mimmob07** [comment]
I'm also experiencing this issue. @JeanSchoeller

**Comment by JeanSchoeller** [comment]
Should be good. Reopen if not. PKGver was not at the right place.
